{% block default_success_reason %}
The expected good value is present within the checked log entry.
{% endblock default_success_reason %}

{% block default_failure_reason %}
A known bad value is present within the checked log entry indicating a problem
{% endblock default_failure_reason %}

{% block default_failure_remediation %}
Run the following Cloud Logging query in the Google Cloud console to find the log entry indicating the problem:

Query:
{query}
{% endblock default_failure_remediation %}

{% block default_uncertain_reason %}
The outcome could not be determined automatically. Manually verify the relevant details in [Cloud Logging](https://cloud.google.com/logging).
{% endblock default_uncertain_reason %}

{% block default_uncertain_remediation %}
Run the following Cloud Logging query in the Google Cloud console to manually review the relevant log entries:

Query:
{query}
{% endblock default_uncertain_remediation %}
