end_time=2024-08-12T23:00:00Z,gke_cluster_name=gke-cluster,location=europe-
west10,project_id=gcpdiag-gke-cluster-autoscaler-rrrr,start_time=2024-08-12T01:00:00Z

gke/image-pull: Analysis and Resolution of Image Pull Failures on GKE clusters.

  This runbook investigates the gke cluster for Image pull failures and recommends remediation
  steps.

  Areas Examined:

  - GKE cluster

  - Stackdriver logs
    
[START]: Starting the image pull error diagnostics
[AUTOMATED STEP]: Check for "Failed to pull image.*not found" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     A container on pod on node failed to pull image because the image was not found in the repository.
     Example log entry:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Refer to the troubleshooting documentation:
     <https://cloud.google.com/kubernetes-engine/docs/troubleshooting#ImagePullBackOff>

[AUTOMATED STEP]: Check for "Failed to pull image.*403 Forbidden" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Image cannot be pulled by a container on Pod, because there are not enough permissions to pull it from the repository.
     Verify the node SA has the correct permissions.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Ensure the node service account has the necessary permissions to pull the image. Refer to the documentation:
     <https://cloud.google.com/artifact-registry/docs/integrate-gke#permissions>

[AUTOMATED STEP]: Check for "Failed to pull image.*lookup.*server misbehaving" log entries.

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     The DNS resolver (metadata server 169.254.169.254:53) on node was unable to resolve the image repository's IP address, preventing image pull. This often indicates issues with networking or DNS configuration.
     Example log entry:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Verify networking and DNS requirements, particularly for Private Google Access. Refer to the documentation:
     <https://cloud.google.com/vpc/docs/configure-private-google-access#requirements>

[AUTOMATED STEP]: Check for "Failed to pull image.*dial tcp.*199.36.153.\d:443: i/o timeout" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Connections from node to restricted.googleapis.com (199.36.153.4/30) or private.googleapis.com (199.36.153.8/30) timed out, preventing image pulls. This may be caused by a firewall rule blocking egress traffic to these IP ranges.
     Example log entry:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Ensure firewall rules permit egress traffic to restricted.googleapis.com (199.36.153.4/30) or private.googleapis.com (199.36.153.8/30). Refer to the documentation:
     <https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity>

[AUTOMATED STEP]: Check for "Failed to pull image.*dial tcp.*i/o timeout" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Connections from node to Google APIs timed out, preventing image pulls. This may be caused by a firewall rule blocking egress traffic to Google APIs. The specific blocked IP range might be indicated in the log entry.
     Example log entry:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]
     Ensure firewall rules permit egress traffic to Google APIs. Refer to the documentation:
     <https://cloud.google.com/kubernetes-engine/docs/concepts/firewall-rules>

[AUTOMATED STEP]: Check for "Failed to pull image.*insufficient_scope" log entries

   - gcpdiag-gke-cluster-autoscaler-rrrr                                  [FAIL]
     [REASON]
     Either user or service account that's trying to pull the image doesn't have the necessary permissions to access it or
     Image doesn't exist.
     Example log entry that would help identify involved objects:

     Cluster name: N/A
     Location: europe-west1-b
     Namespace Name: N/A
     Pod Name: N/A
     Project ID: gcpdiag-gke1-aaaa
     Log Message: N/A
     Reporting Instance: N/A
     Last Timestamp: N/A

     [REMEDIATION]

     1. Verify that the image name is correct.
     2. Ensure the node's service account has the necessary permissions. Refer to the documentation:
     <https://cloud.google.com/kubernetes-engine/docs/troubleshooting/deployed-workloads#image-not-found>

[END]: Finalize `GKE Image Pull runbbok` diagnostics.


