---
title: "dataproc/Check Permissions"
linkTitle: "Check Permissions"
weight: 3
type: docs
description: >
  Check if the permissions are set correctly.
---

**Product**: [Cloud Dataproc](https://cloud.google.com/dataproc)\
**Step Type**: COMPOSITE STEP

### Description

None

### Failure Reason

Service Account {service_account} associated with Dataproc cluster was not found in project {project_id} or cross project (if specified).

### Failure Remediation

Provide the project where the service account resides using the `cross_project` parameter.



<!--
This file is auto-generated. DO NOT EDIT

Make pages changes in the corresponding jinja template
or python code
-->
